### ISSUE TITLE
file “****.key” not found

### ISSUE THREAD

**Issue by escnqh** [archeos/ppt-gui#6]
Working directory created: /tmp/osm-bundler-9PqmrM
BundlerMatching executable path: /home/escnqh/osm-bundler/linux/software/bundler/bin/KeyMatchFull
Sift executable path: /home/escnqh/osm-bundler/linux/software/vlfeat/bin/glx/sift

Processing photo 'kermit006.jpg':
	Extracting features with the SIFT method from VLFeat library...
kermit006.jpg.pgm: 1: kermit006.jpg.pgm: /home/escnqh/osm-bundler/linux/software/vlfeat/bin/glx/sift: not found
Traceback (most recent call last):
  File "./RunBundler.py", line 8, in <module>
    manager.preparePhotos()
  File "/home/escnqh/osm-bundler/linux/osmbundler/__init__.py", line 158, in preparePhotos
    self._preparePhoto(photoInfo)
  File "/home/escnqh/osm-bundler/linux/osmbundler/__init__.py", line 270, in _preparePhoto
    self.extractFeatures(photo)
  File "/home/escnqh/osm-bundler/linux/osmbundler/__init__.py", line 337, in extractFeatures
    self.featureExtractor.extract(photo, self.photoDict[photo])
  File "/home/escnqh/osm-bundler/linux/osmbundler/features/siftvlfeat.py", line 18, in extract
    vlfeatTextFile = open("%s.key" % photo, "r")
IOError: [Errno 2] No such file or directory: 'kermit006.key'

**Comment by escnqh** [comment]
Already solved.

**Comment by onekarlaway** [comment]
How did you solve this problem?
